// Generated by Wrangler by running `wrangler types -c ./config/config.toml`

interface Env {
  KV: KVNamespace
  RUN_ENV: 'prod' | 'development'
  RUN_TYPE: 'prod' | 'dev'
  JWT_ALGORITHMS: '${JWT_ALGORITHMS}' | 'HS256'
  JWT_EXPIRES: '${JWT_EXPIRES}' | '999999999999'
  JWT_ISSUER: '${JWT_ISSUER}' | 'slax-reader-dev'
  IMAGER_CHECK_DIGST_SALT: '${IMAGER_CHECK_DIGST_SALT}' | 'slax-reader'
  GOOGLE_AUTH_PREFIX: '${GOOGLE_AUTH_PREFIX}' | 'http://localhost:8080/?transport=https%3A%2F%2Foauth2.googleapis.com'
  SEARCH_GOOGLE_API: '${SEARCH_GOOGLE_API}' | 'http://localhost:8080/?transport=https%3A%2F%2Fwww.googleapis.com%2Fcustomsearch%2Fv1'
  IMAGE_PREFIX: '${IMAGE_PREFIX}' | 'http://localhost:8787/local/image?key='
  PROXY_IMAGE_PREFIX: '${PROXY_IMAGE_PREFIX}' | 'http://localhost:8787/static/image'
  OPENAI_GATEWAY: '${OPENAI_GATEWAY}' | 'http://localhost:8080/?transport=https%3A%2F%2Fapi.openai.com%2Fv1'
  PROXY_OPENAI_GATEWAY: '${PROXY_OPENAI_GATEWAY}' | 'http://localhost:8080/?transport=https%3A%2F%2Fapi-telegram-sg.slax.app%2Fv1'
  SLAX_READER_BOT_NAME: '${SLAX_READER_BOT_NAME}' | 'slax_reader_bot'
  SLAX_READER_BOT_ID: '${SLAX_READER_BOT_ID}'
  SLAX_READER_BOT_API_ROOT: '${SLAX_READER_BOT_API_ROOT}'
  FRONT_END_URL: '${FRONT_END_URL}' | 'http://localhost:3000'
  APPLE_SIGN_KEY_ID: 'FXYV5RRAR8'
  APPLE_SIGN_TEAM_ID: '8G3A932HJG'
  APPLE_SIGN_CLIENT_ID: 'app.slax.reader'
  STRIPE_ISSUANCE_SCRIPTION_PRICE_ID: 'price_1PqV7vFgBPcC9kF5d1kv2XHr'
  STRIPE_SUBSCRIPTION_HOME: 'https://billing.stripe.com/p/login/test_7sI6oFefc4RybGU9AA'
  SES_SMTP_FROM_ADDRESS: 'no_reply@slax.com'
  SES_SMTP_HOST: 'email-smtp.ap-southeast-1.amazonaws.com'
  OPENAI_API_KEY: string
  HASH_IDS_SALT: string
  JWT_SECRET_TEXT: string
  GOOGLE_CLIENT_ID_TEXT: string
  GOOGLE_CLIENT_SECRET_TEXT: string
  TELEGRAM_BOT_TOKEN: string
  APIFY_API_TOKEN: string
  GOOGLE_SEARCH_KEY: string
  GOOGLE_SEARCH_ENAGINE_ID: string
  AZURE_OPENAI_EASTUS2_KEY: string
  AZURE_OPENAI_JAPAN_EAST_KEY: string
  AZURE_OPENAI_KOREA_CENTRAL_KEY: string
  TURNSTILE_PAYMENT_SECRET_KEY: string
  JINA_API_KEY: string
  SLAX_BROWSER: DurableObjectNamespace<import('./src/worker').SlaxBrowser>
  SLAX_JIEBA: DurableObjectNamespace<import('./src/worker').SlaxJieba>
  WEBSOCKET_SERVER: DurableObjectNamespace<import('./src/worker').SlaxWebSocketServer>
  OSS: R2Bucket
  OSS_PREVIEW: R2Bucket
  DB: D1Database
  DB_FULLTEXT: D1Database
  TWITTER_PARSER: Queue
  FETCH_RETRY_PARSER: Queue
  IMPORT_OTHER: Queue
  VECTORIZE1: VectorizeIndex
  VECTORIZE2: VectorizeIndex
  VECTORIZE3: VectorizeIndex
  VECTORIZE4: VectorizeIndex
  VECTORIZE5: VectorizeIndex
  BROWSER: Fetcher
  AI: Ai
}
declare module '*.wasm' {
  const value: WebAssembly.Module
  export default value
}
