// Generated by Wrangler by running `wrangler types -c ./config/config.toml`

interface Env {
  KV: KVNamespace
  RUN_ENV: 'prod'
  RUN_TYPE: 'prod'
  JWT_ALGORITHMS: '${JWT_ALGORITHMS}'
  JWT_EXPIRES: '${JWT_EXPIRES}'
  JWT_ISSUER: '${JWT_ISSUER}'
  IMAGER_CHECK_DIGST_SALT: '${IMAGER_CHECK_DIGST_SALT}'
  GOOGLE_AUTH_PREFIX: '${GOOGLE_AUTH_PREFIX}'
  SEARCH_GOOGLE_API: '${SEARCH_GOOGLE_API}'
  IMAGE_PREFIX: '${IMAGE_PREFIX}'
  PROXY_IMAGE_PREFIX: '${PROXY_IMAGE_PREFIX}'
  OPENAI_GATEWAY: '${OPENAI_GATEWAY}'
  PROXY_OPENAI_GATEWAY: '${PROXY_OPENAI_GATEWAY}'
  SLAX_READER_BOT_NAME: '${SLAX_READER_BOT_NAME}'
  SLAX_READER_BOT_ID: '${SLAX_READER_BOT_ID}'
  SLAX_READER_BOT_API_ROOT: '${SLAX_READER_BOT_API_ROOT}'
  FRONT_END_URL: '${FRONT_END_URL}'
  OPENAI_API_KEY: string
  HASH_IDS_SALT: string
  JWT_SECRET_TEXT: string
  GOOGLE_CLIENT_ID_TEXT: string
  GOOGLE_CLIENT_SECRET_TEXT: string
  TELEGRAM_BOT_TOKEN: string
  APIFY_API_TOKEN: string
  GOOGLE_SEARCH_KEY: string
  GOOGLE_SEARCH_ENAGINE_ID: string
  AZURE_OPENAI_EASTUS2_KEY: string
  AZURE_OPENAI_JAPAN_EAST_KEY: string
  AZURE_OPENAI_KOREA_CENTRAL_KEY: string
  TURNSTILE_PAYMENT_SECRET_KEY: string
  JINA_API_KEY: string
  SLAX_BROWSER: DurableObjectNamespace<import('./src/worker').SlaxBrowser>
  SLAX_JIEBA: DurableObjectNamespace<import('./src/worker').SlaxJieba>
  WEBSOCKET_SERVER: DurableObjectNamespace<import('./src/worker').SlaxWebSocketServer>
  OSS: R2Bucket
  OSS_PREVIEW: R2Bucket
  DB: D1Database
  DB_FULLTEXT: D1Database
  TWITTER_PARSER: Queue
  FETCH_RETRY_PARSER: Queue
  IMPORT_OTHER: Queue
  VECTORIZE1: VectorizeIndex
  VECTORIZE2: VectorizeIndex
  VECTORIZE3: VectorizeIndex
  VECTORIZE4: VectorizeIndex
  VECTORIZE5: VectorizeIndex
  BROWSER: Fetcher
  AI: Ai
}
declare module '*.wasm' {
  const value: WebAssembly.Module
  export default value
}
