version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: dev-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: slax-reader-backend
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
  pgadmin_data:
