#:schema node_modules/wrangler/config-schema.json
name = "slax-read-api"
main = "../src/worker.ts"
workers_dev = true
compatibility_date = "2024-08-06"
compatibility_flags = ["nodejs_compat_v2"]

browser = { binding = "BROWSER" }

# smart placement
placement = { mode = "smart" }

# observability
[observability]
enabled = true

[vars]
RUN_ENV = "prod"
RUN_TYPE = "prod"

JWT_ALGORITHMS = "${JWT_ALGORITHMS}"
JWT_EXPIRES = "${JWT_EXPIRES}"
JWT_ISSUER = "${JWT_ISSUER}"

IMAGER_CHECK_DIGST_SALT = "${IMAGER_CHECK_DIGST_SALT}"

GOOGLE_AUTH_PREFIX = "${GOOGLE_AUTH_PREFIX}"
SEARCH_GOOGLE_API = "${SEARCH_GOOGLE_API}"

IMAGE_PREFIX = "${IMAGE_PREFIX}"
PROXY_IMAGE_PREFIX = "${PROXY_IMAGE_PREFIX}"
OPENAI_GATEWAY = "${OPENAI_GATEWAY}"
PROXY_OPENAI_GATEWAY = "${PROXY_OPENAI_GATEWAY}"

SLAX_READER_BOT_NAME = "${SLAX_READER_BOT_NAME}"
SLAX_READER_BOT_ID = "${SLAX_READER_BOT_ID}"
SLAX_READER_BOT_API_ROOT = "${SLAX_READER_BOT_API_ROOT}"
FRONT_END_URL = "${FRONT_END_URL}"

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "${HYPERDRIVE_ID}"
localConnectionString = "${LOCAL_CONNECTION_STRING}"

[ai]
binding = "AI"

[[durable_objects.bindings]]
name = "SLAX_BROWSER"
class_name = "SlaxBrowser"
[[durable_objects.bindings]]
name = "SLAX_JIEBA"
class_name = "SlaxJieba"
[[durable_objects.bindings]]
name = "WEBSOCKET_SERVER"
class_name = "SlaxWebSocketServer"
[[durable_objects.bindings]]
name = "MCP_OBJECT"
class_name = "SlaxMcpServer"

[triggers]
crons = ["*/5 * * * *", "0 */1 * * *", "*/15 * * * *"]

[[rules]]
type = "CompiledWasm"
globs = ["**/*.wasm"]
fallthrough = false

## auto-complete

## auto-complete
